name:                fibered-effects
version:             0.1.0.0
github:              "Skyb0rg007/fibered-effects"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skyler.soss@gmail.com"
copyright:           "2022 Skye Soss"

extra-source-files:
- README.md
- CHANGELOG.md

# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/Skyb0rg007/fibered-effects#readme>

dependencies:
- base >= 4.7 && < 5
- comonad
- free
- kan-extensions
- recursion-schemes
- constraints

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFunctor
- DerivingStrategies
- DerivingVia
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- PatternSynonyms
- PolyKinds
- QuantifiedConstraints
- QuasiQuotes
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fibered-effects-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fibered-effects

tests:
  fibered-effects-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fibered-effects
    - hedgehog
